updated readme and contributing for putt-putt-dataset
NDCLab/putt-putt-dataset pull request #5
Opened 2021-12-22 10:16 UTC by SarahMalykke

Updated the readme and contributing for putt-putt @jessb0t 🙂

2022-01-20 18:36 UTC, jessb0t requested changes
@SarahMalykke Thank you for your work on putting together the public face and traceability of the putt-putt-dataset!

I made several comments on specific lines of code.  Also, please update the questionnaires section.  You can look to either [rwe](https://github.com/NDCLab/rwe-dataset/tree/main/materials/questionnaires) or [readAloud-valence](https://github.com/NDCLab/readAloud-valence-dataset/tree/dev/materials/questionnaires) for suggestions on ways to tackle this!

Thank you!

2022-01-20 18:36 UTC, jessb0t commented on materials/flanker_golf_tasks/readme.md
> +This folder contains the protocols, scripts, and stimuli used to create this experimental task.
But this folder doesn't actually contain anything yet?  It should have the full PsychoPy experiment for the flanker (under scripts) and then maybe a detailed overview of the setup of the golf-putting task?  Feel free to collapse the levels and make the flow more intuitive within the "materials" folder as a whole.  The purpose of this folder is to enable replicability of your methods.

2022-01-20 18:36 UTC, jessb0t commented on materials/flanker_golf_tasks/readme.md
> +This folder contains the protocols, scripts, and stimuli used to create this experimental task.
Also, please separate the flanker and golf task materials, since they are independent. :)

2022-02-05 16:54 UTC, SarahMalykke commented
@jessb0t I updated the readme file 🙂 I'll work on the materials folder next time I'm in AHC5, so I can get the flanker files and take pictures of my golf setup

2022-02-09 20:58 UTC, jessb0t approved these changes

2022-02-09 21:06 UTC, merged